#if !defined(ofuscstring_H__36DB8046_25CF_412B_8619_391C20E99D42__INCLUDED_)
#define ofuscstring_H__36DB8046_25CF_412B_8619_391C20E99D42__INCLUDED_
#define STRKEY 6

extern char STR_INSTALL_KEY1[];
extern char STR_INSTALL_KEY2[];
extern char STR_DLL_WININET[];
extern char STR_DLL_ADVAPI[];
extern char STR_DLL_SHELL[];
extern char STR_DLL_SOCKET[];

extern char STR_MAIN_URL[];
extern char STR_MAIN_URL_INITVERSION[];
extern char STR_MAIN_URL_DOWNLOADVERSION[];
extern char STR_MAIN_DLLNAME[];
extern char STR_MAIN_PROCESSNAME[];
extern char STR_MAIN_KEYNAME[];

extern char STR_DLL_INTERNETGETCONNECTEDSTATE[];
extern char STR_DLL_INTERNETGETCONNECTEDSTATEA[];
extern char STR_DLL_INTERNETCONNECT[];
extern char STR_DLL_INTERNETCONNECTA[];
extern char STR_DLL_INTERNETAUTODIAL[];
extern char STR_DLL_INTERNETAUTODIALA[];
extern char STR_DLL_INTERNETAUTODIALHANGUP[];
extern char STR_DLL_INTERNETAUTODIALHANGUPA[];
extern char STR_DLL_INTERNETOPEN[];     
extern char STR_DLL_INTERNETOPENA[];
extern char STR_DLL_INTERNETOPENURL[];
extern char STR_DLL_INTERNETOPENURLA[];
extern char STR_DLL_HTTPQUERYINFO[];
extern char STR_DLL_HTTPQUERYINFOA[];
extern char STR_DLL_INTERNETREADFILE[];
extern char STR_DLL_INTERNETREADFILEA[];
extern char STR_DLL_INTERNETCLOSEHANDLE[];
extern char STR_DLL_INTERNETCLOSEHANDLEA[];
extern char STR_DLL_HTTPOPENREQUEST[];
extern char STR_DLL_HTTPOPENREQUESTA[];
extern char STR_DLL_HTTPSENDREQUEST[];   
extern char STR_DLL_HTTPSENDREQUESTA[];
extern char STR_DLL_HTTPQUERYINFO[];
extern char STR_DLL_HTTPQUERYINFOA[];
extern char STR_DLL_INTERNETQUERYOPTION[];
extern char STR_DLL_INTERNETQUERYOPTIONA[];
extern char STR_DLL_INTERNETSETOPTION[];
extern char STR_DLL_INTERNETSETOPTIONA[];
extern char STR_DLL_INTERNETSETCOOKIE[];
extern char STR_DLL_INTERNETSETCOOKIEA[];
extern char STR_DLL_HTTPADDREQUESTHEADERS[];
extern char STR_DLL_HTTPADDREQUESTHEADERSA[];

extern char STR_DLL_REGOPENKEYEX[];
extern char STR_DLL_REGOPENKEYEXA[];
extern char STR_DLL_REGQUERYVALUEEX[];     
extern char STR_DLL_REGQUERYVALUEEXA[];
extern char STR_DLL_REGOPENKEY[];     
extern char STR_DLL_REGOPENKEYA[];
extern char STR_DLL_REGCREATEKEY[];
extern char STR_DLL_REGCREATEKEYA[];
extern char STR_DLL_REGSETVALUEEX[];
extern char STR_DLL_REGSETVALUEEXA[];
extern char STR_DLL_REGCLOSEKEY[];
extern char STR_DLL_REGCLOSEKEYA[];
extern char STR_DLL_GETUSERNAME[];
extern char STR_DLL_GETUSERNAMEA[];
extern char STR_DLL_GETCOMPUTERNAME[];
extern char STR_DLL_GETCOMPUTERNAMEA[];

extern char STR_DLL_GETSPECIALFOLDERPATH[];
extern char STR_DLL_GETSPECIALFOLDERPATHA[];

extern char STR_DLL_WSASTARTUP[];
extern char STR_DLL_WSASOCKET[];
extern char STR_DLL_WSASOCKETA[];
extern char STR_DLL_WSACLEANUP[];
extern char STR_DLL_CLOSESOCKET[];
extern char STR_DLL_CONNECT[];
extern char STR_DLL_HTONS[];
extern char STR_DLL_INET_ADDR[];

void StringPlainText(void);
#endif
